name: Deploy to GH Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive  # Fetch private content
          fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod
          lfs: true
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: 🔨 Build project
      run: |
        yarn install
        yarn run build

    - name: Deploy project
      run: |
        yarn run deploy

